### ISSUE TITLE
The prohibitive cost of on-chain Linux instances

### ISSUE THREAD

**Issue by zdanl** [cartesi/machine-solidity-step#67]
I was wondering if this can be narrowed down to a hypothetical full-node hardware requirements specification and network size handling emulation workloads and memory distributedly, not in full sync, actually capable of providing decentralized "cloud" resources on a Blockchain network.

> Since the cost of storing a full Cartesi Machine state within the blockchain is prohibitive, all machine states are represented in the blockchain as cryptographic hashes. The contents of those states and memory represented by those hashes are only known off-chain.

**Comment by edubart** [comment]
Sorry, I could not understand your question. Please use the issue tracker here only to report bugs. I suggest for you to check the Cartesi Discord to ask questions or start quick discussions.

In any case, in that phrase the cost is prohibitive because it's impractical to store a cartesi machine state (which can be GBs) onchain, but fraud proof algorithms that uses machine-solidity-step contracts from repository doesn't need to access the whole machine state, it just need to access some hashes of relevant parts of the state to prove whoever is challenging.
